version: "2"
services:
  web:
    build: docker/.
    container_name: test_web
    volumes:
      - ./:/var/web
    ports:
      - "9000:9000"
    depends_on:
      - mysqldb

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    command: /bin/sh -c "cp /var/web/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./:/var/web
    depends_on:
      - web

  mysqldb:
    image: mysql:5.7
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
